package com.trungld.studyforielts.domain.model

import com.trungld.studyforielts.data.local.entity.TopicVocabularyEntity

/** Seed data for the daily-routines A1 vocabulary activity. */
val DAILY_ROUTINES_A1_VOCABULARY: List<TopicVocabularyEntity> = listOf(
    TopicVocabularyEntity(
        id = "daily_routines_wake_up",
        word = "wake up",
        phonetic = "/weɪk ʌp/",
        meaning = "to stop sleeping",
        exampleSentence = "I wake up at 7 every morning.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
    TopicVocabularyEntity(
        id = "daily_routines_get_dressed",
        word = "get dressed",
        phonetic = "/ɡet drest/",
        meaning = "to put on clothes",
        exampleSentence = "She gets dressed before breakfast.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
    TopicVocabularyEntity(
        id = "daily_routines_breakfast",
        word = "breakfast",
        phonetic = "/ˈbrekfəst/",
        meaning = "the first meal of the day",
        exampleSentence = "We have breakfast at eight o'clock.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
    TopicVocabularyEntity(
        id = "daily_routines_go_to_work",
        word = "go to work",
        phonetic = "/ɡoʊ tə wɜːrk/",
        meaning = "to travel to your job",
        exampleSentence = "He goes to work by bus.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
    TopicVocabularyEntity(
        id = "daily_routines_lunch",
        word = "lunch",
        phonetic = "/lʌntʃ/",
        meaning = "a meal eaten in the middle of the day",
        exampleSentence = "I eat lunch at noon.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
    TopicVocabularyEntity(
        id = "daily_routines_relax",
        word = "relax",
        phonetic = "/rɪˈlæks/",
        meaning = "to rest and feel calm",
        exampleSentence = "After dinner, I relax on the sofa.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
    TopicVocabularyEntity(
        id = "daily_routines_dinner",
        word = "dinner",
        phonetic = "/ˈdɪnər/",
        meaning = "the main meal of the day, usually in the evening",
        exampleSentence = "We have dinner together every night.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
    TopicVocabularyEntity(
        id = "daily_routines_go_to_bed",
        word = "go to bed",
        phonetic = "/ɡoʊ tə bed/",
        meaning = "to get into bed to sleep",
        exampleSentence = "The children go to bed at nine.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
    TopicVocabularyEntity(
        id = "daily_routines_brush_teeth",
        word = "brush teeth",
        phonetic = "/brʌʃ tiːθ/",
        meaning = "to clean your teeth with a toothbrush",
        exampleSentence = "I brush my teeth twice a day.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
    TopicVocabularyEntity(
        id = "daily_routines_take_a_shower",
        word = "take a shower",
        phonetic = "/teɪk ə ˈʃaʊər/",
        meaning = "to wash your body under running water",
        exampleSentence = "He takes a shower every morning.",
        topic = DAILY_ROUTINES_TOPIC,
        cefrLevel = DAILY_ROUTINES_CEFR,
        skill = "vocabulary",
    ),
)
